SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE (SEX_UPON_OUTCOME like 'Neutered%' 
OR SEX_UPON_OUTCOME like 'Spayed%')
AND SEX_UPON_INTAKE like 'Intact%'
ORDER BY ANIMAL_ID;

# SELECT ANIMAL_ID FROM ANIMAL_INS WHERE SEX_UPON_INTAKE like 'Intact%'